######################################################################
# Automatically generated by qmake (2.01a) Thu May 29 19:38:14 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtform_hello.cpp
